### ISSUE TITLE
Creating an NFT with Solmate guide would lock funds in contract

### ISSUE THREAD

**Issue by abcoathup** [onbjerg/foundry-book#133]
Error in guide: https://onbjerg.github.io/foundry-book/tutorials/solmate-nft.html

Withdraw function uses OpenZeppelin PullPayment but mint function doesn't transfer funds to [escrow](https://github.com/OpenZeppelin/openzeppelin-contracts/blob/76fca3aec8e6ce2caf1c9c9a2c8396fe0882591a/contracts/security/PullPayment.sol#L67)

Funds would be locked in contract.  
Guide should include test to check funds can be withdrawn.

Guide doesn't compile as Nft used for both contract and test contract.

**Comment by dmfxyz** [comment]
Addressed the compiling issues in #137

**Comment by abcoathup** [comment]
Thanks @dmfxyz for fixing the tutorial.  Didn't want someone to copypasta and end up with locked funds.
