### ISSUE TITLE
No guidance on how to import "cheats.expectRevert"

### ISSUE THREAD

**Issue by paulrberg** [onbjerg/foundry-book#143]
While reading the [Writing Tests](https://book.getfoundry.sh/forge/writing-tests.html#writing-tests) chapter, I stumbled upon the following code snippet:

```solidity
function testCannotSubtract43() public {
    cheats.expectRevert(abi.encodeWithSignature("Panic(uint256)", 0x11));
    testNumber -= 43;
}
```

I tried to run it but I got the following error:

```
Error:
   0: Compiler run failed
      DeclarationError: Undeclared identifier.
        --> /Users/paulrberg/workspace/templates/foundry-template/test/Contract.t.sol:22:9:
         |
      22 |         cheats.expectRevert(abi.encodeWithSignature("Panic(uint256)", 0x11));
         |         ^^^^^^
```

It looks like the docs are not showing how to import and initialize the `cheats` when first mentioning them.

**Comment by onbjerg** [comment]
We should just refer to the next chapter instead of going into importing cheatcodes in the "Writing Tests" chapter, otherwise we will experience some bloat

**Comment by paulrberg** [comment]
> We should just refer to the next chapter

That'd work.

**Comment by Sabnock01** [comment]
Wouldn't it just be simple enough to add the import and contract code to the snippet just like in the ds-test examples at the top of the page?

**Comment by onbjerg** [comment]
The main issue is that the cheatcode is in a separate interface (it's not in DSTest), so we would have to include a "Cheats" interface on this specific page and explain why it is there. I'd rather we link to `expectRevert` in the reference and guide people to the next guide that is about cheatcodes :)
