### ISSUE TITLE
No explanation for what is "μ" in test outputs

### ISSUE THREAD

**Issue by paulrberg** [onbjerg/foundry-book#146]
Every now and then, the `μ` symbol (Greek letter mu) appears in my test outputs. However, I couldn't find this documented in the [Tests](https://book.getfoundry.sh/forge/tests.html) chapter of the book.

**Comment by mds1** [comment]
The number after `μ` is the mean gas used across all fuzz runs, and the one after `~` is the median gas used across those same fuzz runs. I can probably get a PR in for this later today if you don't beat me to it 🙂 

https://github.com/gakonst/foundry/blob/b8125de1d7eec22baca83b24fe141b1d262c1426/forge/src/runner.rs#L96

**Comment by onbjerg** [comment]
Not sure where this is supposed to fit - honestly, this should probably be in the Forge command reference (TBD)

**Comment by mds1** [comment]
Until that page is created, I think https://book.getfoundry.sh/forge/fuzz-testing.html seems like the appropriate spot by adding an "Interpreting Results" section or something similar

**Comment by paulrberg** [comment]
Thanks @mds1 for explaining this.
