### ISSUE TITLE
Document new `label` cheatcode

### ISSUE THREAD

**Issue by onbjerg** [onbjerg/foundry-book#29]
Ref: https://github.com/gakonst/foundry/pull/629

**Comment by ZeroEkkusu** [comment]
We should make either a new label e.g. "new feature" and label these issues with it, or a new, special issue where we would dump new features to be documented, like this:

### Forge
- [ ] `--gas-report`
- [ ] ...

### Cheatcodes
- [ ] `label`
- [ ] ...

### ...
